### ISSUE TITLE
Using ' in the section name fails "Add more action" in program Rules

### ISSUE THREAD

**Issue by talexie** [dhis2/dhis2-core#153]
Using single quotes (') in the section name fails "Add more action" in program Rules during creation. See line 255 circled in the snapshot added.

Quick fix is to avoid using single quotes and use double quotes.
![bugs](https://cloud.githubusercontent.com/assets/8069419/18834961/4f9ac3ee-83e8-11e6-9f85-77121dfc92b7.png)

**Comment by Bekkalizer** [comment]
Reported by Calle, on 2.24 - the following error message was given when saving a new or updated rule: 

> HTTP Status 404 - There is no Action mapped for namespace [/dhis-web-maintenance-program] and action name [addProgramRule] associated with context path [/staging]

**Comment by larshelge** [comment]
Please report this in jira.dhis2.org.
