### ISSUE TITLE
Datasets for Approval in Reports Module are limited to 50 (page 1) due to the api query used

### ISSUE THREAD

**Issue by talexie** [dhis2/dhis2-core#204]
Datasets for Approval in Reports Module are limited to 50 (page 1) due to the api query used
![dataset approval bug](https://cloud.githubusercontent.com/assets/8069419/19146146/ae4f2c66-8ba1-11e6-8f03-57a988c41a9c.png)

"..api/dataSets.json?fields=id,displayName,periodType,workflow,categoryCombo[id,displayName]"

This line needs to be changed to 

"../api/dataSets.json?fields=id,displayName,periodType,workflow,categoryCombo[id,displayName]&paging=false"

**Comment by larshelge** [comment]
Fixed now in master, 2.25, 2.24.

23e3a385b5d324ca57df6a2d0d07984e31d7870d @larshelge
