### ISSUE TITLE
Translations api endpoint unavailable in 2.25+

### ISSUE THREAD

**Issue by Awnage** [dhis2/dhis2-core#264]
Per the [docs](https://dhis2.github.io/dhis2-docs/master/en/developer/html/webapi_translations.html#d0e10804), the translations api should be available via `/api/translations` and/or `/api/25/translations`. This endpoint is returning 404 errors in 2.25. The endpoint was working in 2.24. Links to replicate issue:
- [play.dhis2.org/demo](https://play.dhis2.org/demo/api/translations)
- [play.dhis2.org/dev](https://play.dhis2.org/dev/api/translations)

It looks like an undocumented `api/OBJECTTYPE/UID/translations` endpoint does work. 
- eg: (https://play.dhis2.org/dev/api/25/categories/KfdsGBcoiCa/translations)

**Comment by jason-p-pickering** [comment]
@mortenoh can you comment on this?

**Comment by jason-p-pickering** [comment]
@vietnguyen could you have a look at this and update the docs if needed?

**Comment by larshelge** [comment]
Please report in https://jira.dhis2.org
