### ISSUE TITLE
Importing dependency program metadata

### ISSUE THREAD

**Issue by Bekkalizer** [dhis2/dhis2-core#280]
When importing updated metadata for a program, the updated programStageTrackedEntityAttribute rows fails with a uniqueConstraintException from the database. It seems the underlying import logic does not recognize that the rows exists from before, and the import treats these rows as inserts, not updates. 

1. Export any tracker program with dependencies in 2.25.
2. Import the same program in the same instance.

**Comment by mortenoh** [comment]
Fixed in 225/master
